#报名
sign.score: 300
#点赞
give.score: 20
#连续点赞2天
give.score.two: 10
#连续点赞4天
give.score.four: 20
#连续点赞6天
give.score.six: 40
#连续点赞8天
give.score.eight: 60
#连续点赞10天
give.score.ten: 80
#连续点赞12天
give.score.twelve: 100
#阅读奖励
give.read: 10
#阅读奖励积分总上限
give.read.total: 3000

#邀请报名奖励人数上线
give.invite.num: 20
#邀请报名奖励
give.invite: 300
#邀请报名奖励2人
give.invite.two: 100
#邀请报名奖励4人
give.invite.four: 150
#邀请报名奖励6人
give.invite.six: 200
#邀请报名奖励8人
give.invite.eight: 250
#邀请报名奖励10人
give.invite.ten: 300

#签到验票奖励
give.sign: 300

#一级推荐奖励
give.recommend.one: 300
#二级推荐奖励
give.recommend.two: 150
